In [4]:
import pandas as pd 
import numpy as np
import requests
from io import StringIO
from datetime import timedelta, datetime
from utils.functions_evaluation import *
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

/Users/stefania/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [ ]:
# Loading surveillance data for evaluation: last surveillance file
season = '2024-2025'

if season == '2023-2024':
    start_date = datetime(2023, 9, 9)  
    surveillance_file = "target-hospital-admissions_2024-04-27.csv"
    horizon_to_start = 9
elif season == '2024-2025':
    start_date = datetime(2024, 11, 16)  # Adjusted to the latest date in the surveillance data
    surveillance_file = "target-hospital-admissions_2025-05-31.csv"
    horizon_to_start = 3

state = 'US'
github_repo = "cdcepi/FluSight-forecast-hub"
github_directory = "auxiliary-data/target-data-archive"

df_surv = loading_surveillance_eval(start_date, github_repo, github_directory, surveillance_file, state, horizon_to_start)
if season == '2023-2024':
    df_surv.to_csv("../../../input_data/target-hospital-admissions_2025-05-31.csv", index = False)
elif season == '2024-2025':
    df_surv.to_csv("../../../input_data/target-hospital-admissions_2025-05-31.csv", index=False)
df_surv.head()

           date location location_name  hospitalizations  weekly_rate  horizon
7707 2024-11-30       US            US            4270.0     1.274951        3
7091 2024-12-07       US            US            6276.0     1.873909        4
2884 2024-12-14       US            US            9143.0     2.729947        5
4055 2024-12-21       US            US           15381.0     4.592510        6
5278 2024-12-28       US            US           27617.0     8.245975        7

In [ ]:
if season == '2024-2025':
    # add +10 to horizon to start to then merge correctly dataframes
    df_surv['horizon'] = df_surv['horizon'] + 13
    # skip the last dates in May because under epidemic threshold
    df_surv = df_surv[df_surv['date'] <= '2025-05-03']
df_surv.head()

           date location location_name  hospitalizations  weekly_rate  horizon
7707 2024-11-30       US            US            4270.0     1.274951       16
7091 2024-12-07       US            US            6276.0     1.873909       17
2884 2024-12-14       US            US            9143.0     2.729947       18
4055 2024-12-21       US            US           15381.0     4.592510       19
5278 2024-12-28       US            US           27617.0     8.245975       20

In [ ]:
adaptive_ensemble2_path = "../output_data/adaptive_ensemble2/"
original_ensembles_path = "../output_data/original_ensembles/"
horizon_to_date = df_surv.set_index('horizon')['date'].to_dict()
surv_lookup = df_surv[['date', 'hospitalizations']].drop_duplicates()
k_values = [0.05, 0.15, 0.25, 0.50, 0.75]
loss_function = 'rmse'
dict_k_wis_rounds = {}
dict_k_mae_rounds = {}
alphas=[0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]
for k in k_values:
    dict_wis_rounds = {}
    dict_mae_rounds = {}
    unique_dates = df_surv['date'].sort_values().unique()[:-2]
    for date in unique_dates:
        print(f"Processing date: {date} with k={k}")
        if date == datetime(2025, 1, 25):
            continue
        # Adaptive Ensemble2
        full_path_adaptive_ensemble2 = f"{adaptive_ensemble2_path}/{date.strftime('%Y-%m-%d')}_{k}_{loss_function}_{season}.csv"
        df_adaptive_ensemble2 = import_ensemble2(full_path_adaptive_ensemble2, surv_lookup, horizon_to_date)
        wis_list_adens2, wis_mean_adens2, wmape_adens2 = compute_dict_WIS_AE(df_adaptive_ensemble2, alphas)
        # Orginal Ensemble2
        full_path_original_ensemble2 = f"{original_ensembles_path}/Ensemble_Ens2_USnational_{season}.csv"
        df_original_ensemble2 = import_ensemble_original(full_path_original_ensemble2, df_surv, date)
        wis_list_original_ens2, wis_mean_original_ens2, wmape_original_ens2 = compute_dict_WIS_AE(df_original_ensemble2, alphas)
        # Original Ensemble - Scenario A
        full_path_original_ensembleA = f"{original_ensembles_path}/Ensemble_A_USnational_{season}.csv"
        df_original_ensembleA = import_ensemble_original(full_path_original_ensembleA, df_surv, date)
        wis_list_original_ensA, wis_mean_original_ensA, wmape_original_ensA = compute_dict_WIS_AE(df_original_ensembleA, alphas)
        # Original Ensemble - Scenario B
        full_path_original_ensembleB = f"{original_ensembles_path}/Ensemble_B_USnational_{season}.csv"
        df_original_ensembleB = import_ensemble_original(full_path_original_ensembleB, df_surv, date)
        wis_list_original_ensB, wis_mean_original_ensB, wmape_original_ensB = compute_dict_WIS_AE(df_original_ensembleB, alphas)
        # Original Ensemble - Scenario C
        full_path_original_ensembleC = f"{original_ensembles_path}/Ensemble_C_USnational_{season}.csv"
        df_original_ensembleC = import_ensemble_original(full_path_original_ensembleC, df_surv, date)
        wis_list_original_ensC, wis_mean_original_ensC, wmape_original_ensC = compute_dict_WIS_AE(df_original_ensembleC, alphas)
        # Original Ensemble - Scenario D
        full_path_original_ensembleD = f"{original_ensembles_path}/Ensemble_D_USnational_{season}.csv"
        df_original_ensembleD = import_ensemble_original(full_path_original_ensembleD, df_surv, date)
        wis_list_original_ensD, wis_mean_original_ensD, wmape_original_ensD = compute_dict_WIS_AE(df_original_ensembleD, alphas)
        # Original Ensemble - Scenario E
        full_path_original_ensembleE = f"{original_ensembles_path}/Ensemble_E_USnational_{season}.csv"
        df_original_ensembleE = import_ensemble_original(full_path_original_ensembleE, df_surv, date)
        wis_list_original_ensE, wis_mean_original_ensE, wmape_original_ensE = compute_dict_WIS_AE(df_original_ensembleE, alphas)
        # Original Ensemble - Scenario F
        full_path_original_ensembleF = f"{original_ensembles_path}/Ensemble_F_USnational_{season}.csv"
        df_original_ensembleF = import_ensemble_original(full_path_original_ensembleF, df_surv, date)
        wis_list_original_ensF, wis_mean_original_ensF, wmape_original_ensF = compute_dict_WIS_AE(df_original_ensembleF, alphas)
        # Store WIS and AE results
        dict_wis_rounds[date] = [wis_mean_adens2, wis_mean_original_ens2, wis_mean_original_ensA, wis_mean_original_ensB, wis_mean_original_ensC, wis_mean_original_ensD, wis_mean_original_ensE, wis_mean_original_ensF]
        dict_mae_rounds[date] = [wmape_adens2, wmape_original_ens2, wmape_original_ensA, wmape_original_ensB, wmape_original_ensC, wmape_original_ensD, wmape_original_ensE, wmape_original_ensF]
    k_perc = int(k * 100)
    dict_k_wis_rounds[k_perc] = dict_wis_rounds
    dict_k_mae_rounds[k_perc] = dict_mae_rounds

Processing date: 2024-11-30 00:00:00 with k=0.05
Processing date: 2024-12-07 00:00:00 with k=0.05
Processing date: 2024-12-14 00:00:00 with k=0.05
Processing date: 2024-12-21 00:00:00 with k=0.05
Processing date: 2024-12-28 00:00:00 with k=0.05
Processing date: 2025-01-04 00:00:00 with k=0.05
Processing date: 2025-01-11 00:00:00 with k=0.05
Processing date: 2025-01-18 00:00:00 with k=0.05
Processing date: 2025-01-25 00:00:00 with k=0.05
Processing date: 2025-02-01 00:00:00 with k=0.05
Processing date: 2025-02-08 00:00:00 with k=0.05
Processing date: 2025-02-15 00:00:00 with k=0.05
Processing date: 2025-02-22 00:00:00 with k=0.05
Processing date: 2025-03-01 00:00:00 with k=0.05
Processing date: 2025-03-08 00:00:00 with k=0.05
Processing date: 2025-03-15 00:00:00 with k=0.05
Processing date: 2025-03-22 00:00:00 with k=0.05
Processing date: 2025-03-29 00:00:00 with k=0.05
Processing date: 2025-04-05 00:00:00 with k=0.05
Processing date: 2025-04-12 00:00:00 with k=0.05
Processing date: 2025-04-19 00:00:00 with k=0.05
Processing date: 2024-11-30 00:00:00 with k=0.15
Processing date: 2024-12-07 00:00:00 with k=0.15
Processing date: 2024-12-14 00:00:00 with k=0.15
Processing date: 2024-12-21 00:00:00 with k=0.15
Processing date: 2024-12-28 00:00:00 with k=0.15
Processing date: 2025-01-04 00:00:00 with k=0.15
Processing date: 2025-01-11 00:00:00 with k=0.15
Processing date: 2025-01-18 00:00:00 with k=0.15
Processing date: 2025-01-25 00:00:00 with k=0.15
Processing date: 2025-02-01 00:00:00 with k=0.15
Processing date: 2025-02-08 00:00:00 with k=0.15
Processing date: 2025-02-15 00:00:00 with k=0.15
Processing date: 2025-02-22 00:00:00 with k=0.15
Processing date: 2025-03-01 00:00:00 with k=0.15
Processing date: 2025-03-08 00:00:00 with k=0.15
Processing date: 2025-03-15 00:00:00 with k=0.15
Processing date: 2025-03-22 00:00:00 with k=0.15
Processing date: 2025-03-29 00:00:00 with k=0.15
Processing date: 2025-04-05 00:00:00 with k=0.15
Processing date: 2025-04-12 00:00:00 with k=0.15
Processing date: 2025-04-19 00:00:00 with k=0.15
Processing date: 2024-11-30 00:00:00 with k=0.25
Processing date: 2024-12-07 00:00:00 with k=0.25
Processing date: 2024-12-14 00:00:00 with k=0.25
Processing date: 2024-12-21 00:00:00 with k=0.25
Processing date: 2024-12-28 00:00:00 with k=0.25
Processing date: 2025-01-04 00:00:00 with k=0.25
Processing date: 2025-01-11 00:00:00 with k=0.25
Processing date: 2025-01-18 00:00:00 with k=0.25
Processing date: 2025-01-25 00:00:00 with k=0.25
Processing date: 2025-02-01 00:00:00 with k=0.25
Processing date: 2025-02-08 00:00:00 with k=0.25
Processing date: 2025-02-15 00:00:00 with k=0.25
Processing date: 2025-02-22 00:00:00 with k=0.25
Processing date: 2025-03-01 00:00:00 with k=0.25
Processing date: 2025-03-08 00:00:00 with k=0.25
Processing date: 2025-03-15 00:00:00 with k=0.25
Processing date: 2025-03-22 00:00:00 with k=0.25
Processing date: 2025-03-29 00:00:00 with k=0.25
Processing date: 2025-04-05 00:00:00 with k=0.25
Processing date: 2025-04-12 00:00:00 with k=0.25
Processing date: 2025-04-19 00:00:00 with k=0.25
Processing date: 2024-11-30 00:00:00 with k=0.5
Processing date: 2024-12-07 00:00:00 with k=0.5
Processing date: 2024-12-14 00:00:00 with k=0.5
Processing date: 2024-12-21 00:00:00 with k=0.5
Processing date: 2024-12-28 00:00:00 with k=0.5
Processing date: 2025-01-04 00:00:00 with k=0.5
Processing date: 2025-01-11 00:00:00 with k=0.5
Processing date: 2025-01-18 00:00:00 with k=0.5
Processing date: 2025-01-25 00:00:00 with k=0.5
Processing date: 2025-02-01 00:00:00 with k=0.5
Processing date: 2025-02-08 00:00:00 with k=0.5
Processing date: 2025-02-15 00:00:00 with k=0.5
Processing date: 2025-02-22 00:00:00 with k=0.5
Processing date: 2025-03-01 00:00:00 with k=0.5
Processing date: 2025-03-08 00:00:00 with k=0.5
Processing date: 2025-03-15 00:00:00 with k=0.5
Processing date: 2025-03-22 00:00:00 with k=0.5
Processing date: 2025-03-29 00:00:00 with k=0.5
Processing date: 2025-04-05 00:00:00 with k=0.5
Processing date: 2025-04-12 00:00:00 with k=0.5
Processing date: 2025-04-19 00:00:00 with k=0.5
Processing date: 2024-11-30 00:00:00 with k=0.75
Processing date: 2024-12-07 00:00:00 with k=0.75
Processing date: 2024-12-14 00:00:00 with k=0.75
Processing date: 2024-12-21 00:00:00 with k=0.75
Processing date: 2024-12-28 00:00:00 with k=0.75
Processing date: 2025-01-04 00:00:00 with k=0.75
Processing date: 2025-01-11 00:00:00 with k=0.75
Processing date: 2025-01-18 00:00:00 with k=0.75
Processing date: 2025-01-25 00:00:00 with k=0.75
Processing date: 2025-02-01 00:00:00 with k=0.75
Processing date: 2025-02-08 00:00:00 with k=0.75
Processing date: 2025-02-15 00:00:00 with k=0.75
Processing date: 2025-02-22 00:00:00 with k=0.75
Processing date: 2025-03-01 00:00:00 with k=0.75
Processing date: 2025-03-08 00:00:00 with k=0.75
Processing date: 2025-03-15 00:00:00 with k=0.75
Processing date: 2025-03-22 00:00:00 with k=0.75
Processing date: 2025-03-29 00:00:00 with k=0.75
Processing date: 2025-04-05 00:00:00 with k=0.75
Processing date: 2025-04-12 00:00:00 with k=0.75
Processing date: 2025-04-19 00:00:00 with k=0.75

In [8]:
# Create df_wis dataframe to store WIS results
rows = []
for k, group_data in dict_k_wis_rounds.items():
    for timestamp, values in group_data.items():
        rows.append({
            'k_perc': k,
            'week': timestamp,
            'wis_adaptive_ensemble2': values[0],
            'wis_original_ensemble2': values[1],
            'wis_original_ensembleA': values[2],
            'wis_original_ensembleB': values[3],
            'wis_original_ensembleC': values[4],
            'wis_original_ensembleD': values[5],
            'wis_original_ensembleE': values[6],
            'wis_original_ensembleF': values[7],
            'wis_rel_original2': values[0] / values[1],
            'wis_rel_originalA': values[0] / values[2],
            'wis_rel_originalB': values[0] / values[3],
            'wis_rel_originalC': values[0] / values[4],
            'wis_rel_originalD': values[0] / values[5],
            'wis_rel_originalE': values[0] / values[6],
            'wis_rel_originalF': values[0] / values[7]
        })
df_wis = pd.DataFrame(rows)
df_wis.to_csv(f"../output_data/performance_adaptive_ensemble/wis_performance_{loss_function}_{season}.csv", index=False)

In [9]:
# Create df_mae dataframe to store MAE results
rows = []
for k, group_data in dict_k_mae_rounds.items():
    for timestamp, values in group_data.items():
        rows.append({
            'k_perc': k,
            'week': timestamp,
            'mae_adaptive_ensemble2': values[0],
            'mae_original_ensemble2': values[1],
            'mae_original_ensembleA': values[2],
            'mae_original_ensembleB': values[3],
            'mae_original_ensembleC': values[4],
            'mae_original_ensembleD': values[5],
            'mae_original_ensembleE': values[6],
            'mae_original_ensembleF': values[7],
            'mae_rel_original2': values[0] / values[1],
            'mae_rel_originalA': values[0] / values[2],
            'mae_rel_originalB': values[0] / values[3],
            'mae_rel_originalC': values[0] / values[4],
            'mae_rel_originalD': values[0] / values[5],
            'mae_rel_originalE': values[0] / values[6],
            'mae_rel_originalF': values[0] / values[7]
        })
df_mae = pd.DataFrame(rows)
df_mae.to_csv(f"../output_data/performance_adaptive_ensemble/mae_performance_{loss_function}_{season}.csv", index=False)

Check results and compute statistics (median and IQR)

In [4]:
season = '2023-2024'

In [18]:
if season == '2024-2025':
    df_wis = pd.read_csv("../output_data/performance_adaptive_ensemble/wis_performance_wmape_2024-2025.csv")
    df_mae = pd.read_csv("../output_data/performance_adaptive_ensemble/mae_performance_wmape_2024-2025.csv")
elif season == '2023-2024':
    df_wis = pd.read_csv("../output_data/performance_adaptive_ensemble/wis_performance_wmape_2023-2024.csv")
    df_mae = pd.read_csv("../output_data/performance_adaptive_ensemble/mae_performance_wmape_2023-2024.csv")

In [19]:
if season == '2024-2025':
    df_wis = df_wis[df_wis['week'] <= '2025-03-22']
    df_mae = df_mae[df_mae['week'] <= '2025-03-22']
else:
    df_wis = df_wis[df_wis['week'] >= '2023-11-11']
    df_mae = df_mae[df_mae['week'] >= '2023-11-11']
    df_wis = df_wis[df_wis['week'] <= '2024-03-23']
    df_mae = df_mae[df_mae['week'] <= '2024-03-23']

In [20]:
# define IQR function
def iqr_low(x):
    return np.percentile(x, 25)
def iqr_high(x):
    return np.percentile(x, 75)

# group by k_perc and calculate median and IQR for each group
df_wis.groupby('k_perc').agg({
    'wis_rel_original2': ['median', iqr_low, iqr_high],
})

       wis_rel_original2
                  median   iqr_low  iqr_high
k_perc
5               0.957658  0.795113  1.045843
15              0.973137  0.850132  1.038979
25              0.985911  0.903327  1.044192
50              0.990416  0.956841  1.035469
75              0.994883  0.980335  1.016673

In [21]:
# group by k_perc and calculate median and IQR for each group
df_mae.groupby('k_perc').agg({
    'mae_rel_original2': ['median', iqr_low, iqr_high],
})

       mae_rel_original2
                  median   iqr_low  iqr_high
k_perc
5               1.144568  0.655301  1.255537
15              0.973511  0.599385  1.181088
25              0.933964  0.603967  1.108712
50              0.869584  0.535379  0.966780
75              0.790693  0.693275  0.891205