In [ ]:
import pandas as pd 
import numpy as np
import requests
from io import StringIO
from datetime import timedelta, datetime
from utils.functions_evaluation import *
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

/home/sfiandrino/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

In [20]:
season = "2024-2025"
if season == "2023-2024":
    start_date = datetime(2023, 9, 1)
else:
    start_date = datetime(2024, 11, 16)

github_repo = "cdcepi/FluSight-forecast-hub"
github_directory = "auxiliary-data/target-data-archive"
if season == "2023-2024":
    surveillance_file = "target-hospital-admissions_2024-04-27.csv"
    horizon_to_start = 9
else:
    surveillance_file = "target-hospital-admissions_2025-05-31.csv"
    horizon_to_start = 3

In [21]:
# Loading surveillance data for evaluation: last surveillance file for all states 
df_surv = loading_surveillance_eval(start_date, github_repo, github_directory, surveillance_file, horizon_to_start)
df_surv = df_surv[df_surv['location'] != 'US']
df_surv.head()

           date location location_name  hospitalizations  weekly_rate  horizon
1559 2024-11-30       36      New York             145.0     0.740884        3
7854 2024-11-30       56       Wyoming               7.0     1.198513        3
4221 2024-11-30       29      Missouri              41.0     0.661701        3
4384 2024-11-30       02        Alaska               9.0     1.227151        3
7410 2024-11-30       20        Kansas              20.0     0.680146        3

In [22]:
if season == '2024-2025':
    # add +10 to horizon to start
    df_surv['horizon'] = df_surv['horizon'] + 13
df_surv.head()

           date location location_name  hospitalizations  weekly_rate  horizon
1559 2024-11-30       36      New York             145.0     0.740884       16
7854 2024-11-30       56       Wyoming               7.0     1.198513       16
4221 2024-11-30       29      Missouri              41.0     0.661701       16
4384 2024-11-30       02        Alaska               9.0     1.227151       16
7410 2024-11-30       20        Kansas              20.0     0.680146       16

In [23]:
if season == '2024-2025':
    df_surv = df_surv[df_surv['date'] <= '2025-05-03']

In [35]:
adaptive_ensemble2_path = "../output_data/adaptive_ensemble2"
original_ensembles_path = "../output_data/original_ensembles"
horizon_to_date = df_surv.set_index('horizon')['date'].to_dict()
k_values = [0.05, 0.15, 0.25, 0.50, 0.75]
loss_function = 'wmape'
dict_k_wis_rounds_states = {}
dict_k_mae_rounds_states = {}
alphas=[0.02, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]

for state in df_surv['location'].unique():
    print('Processing state:', state)
    dict_k_wis_rounds = {}
    dict_k_mae_rounds = {}
    df_surv_state = df_surv[df_surv['location'] == state]
    surv_lookup = df_surv_state[['date', 'hospitalizations']].drop_duplicates()
    for k in k_values:
        dict_wis_rounds = {}
        dict_mae_rounds = {}
        unique_dates = df_surv_state['date'].sort_values().unique()[:-1]
        for date in unique_dates:
            if date == datetime(2025, 1, 25):
                continue
            # Adaptive Ensemble2
            full_path_adaptive_ensemble2 = f"{adaptive_ensemble2_path}/{date.strftime('%Y-%m-%d')}_{k}_{loss_function}_{state}_{season}.csv"
            df_adaptive_ensemble2 = import_ensemble2(full_path_adaptive_ensemble2, surv_lookup, horizon_to_date)
            wis_mean_adens2, wmape_adens2 = compute_dict_WIS_AE(df_adaptive_ensemble2, alphas)
            # Orginal Ensemble2
            full_path_original_ensemble2 = f"{original_ensembles_path}/Ensemble_Ens2_{state}_{season}.csv"
            df_original_ensemble2 = import_ensemble_original(full_path_original_ensemble2, df_surv_state, date)
            wis_mean_original_ens2, wmape_original_ens2 = compute_dict_WIS_AE(df_original_ensemble2, alphas)
            dict_wis_rounds[date] = [wis_mean_adens2,wis_mean_original_ens2]
            dict_mae_rounds[date] = [wmape_adens2, wmape_original_ens2]
        k_perc = int(k * 100)
        dict_k_wis_rounds[k_perc] = dict_wis_rounds
        dict_k_mae_rounds[k_perc] = dict_mae_rounds
    dict_k_wis_rounds_states[state] = dict_k_wis_rounds
    dict_k_mae_rounds_states[state] = dict_k_mae_rounds

Processing state: 36
Processing state: 56
Processing state: 29
Processing state: 02
Processing state: 20
Processing state: 09
Processing state: 17
Processing state: 16
Processing state: 39
Processing state: 28
Processing state: 42
Processing state: 08
Processing state: 26
Processing state: 33
Processing state: 37
Processing state: 31
Processing state: 01
Processing state: 18
Processing state: 40
Processing state: 22
Processing state: 12
Processing state: 11
Processing state: 34
Processing state: 54
Processing state: 41
Processing state: 46
Processing state: 05
Processing state: 19
Processing state: 21
Processing state: 04
Processing state: 24
Processing state: 23
Processing state: 38
Processing state: 27
Processing state: 45
Processing state: 15
Processing state: 25
Processing state: 32
Processing state: 55
Processing state: 47
Processing state: 44
Processing state: 48
Processing state: 50
Processing state: 30
Processing state: 53
Processing state: 06
Processing state: 51
Processing state: 10
Processing state: 72
Processing state: 35
Processing state: 49
Processing state: 13

In [36]:
dict_k_mae_rounds_states

{'36': {5: {Timestamp('2024-11-30 00:00:00'): [0.6389500947752096,
    0.7514762759160323],
   Timestamp('2024-12-07 00:00:00'): [0.6304231484436431, 0.7444453760247514],
   Timestamp('2024-12-14 00:00:00'): [0.6272529782462333, 0.7375781082481669],
   Timestamp('2024-12-21 00:00:00'): [0.6128652476952344, 0.7326402596782234],
   Timestamp('2024-12-28 00:00:00'): [0.5927946713149957, 0.73940764307452],
   Timestamp('2025-01-04 00:00:00'): [0.5794135632787416, 0.7647028279964657],
   Timestamp('2025-01-11 00:00:00'): [0.5845786689750962, 0.7765903425670083],
   Timestamp('2025-01-18 00:00:00'): [0.6125171897909326, 0.7883116395242049],
   Timestamp('2025-02-01 00:00:00'): [0.6477971919832032, 0.8036813036590352],
   Timestamp('2025-02-08 00:00:00'): [0.6555328497705146, 0.8108280334147248],
   Timestamp('2025-02-15 00:00:00'): [0.6732398363533795, 0.8144796113574626],
   Timestamp('2025-02-22 00:00:00'): [0.68743988500668, 0.8213379896443739],
   Timestamp('2025-03-01 00:00:00'): [0.7060467986881837, 0.8278092183545981],
   Timestamp('2025-03-08 00:00:00'): [0.7055184656219105, 0.8321681347362905],
   Timestamp('2025-03-15 00:00:00'): [0.7211309945078765, 0.8321149890307794],
   Timestamp('2025-03-22 00:00:00'): [0.7374680368445122, 0.8278516916799459],
   Timestamp('2025-03-29 00:00:00'): [0.7389179401800121, 0.8202341428887191],
   Timestamp('2025-04-05 00:00:00'): [0.761888834988992, 0.8184757677574004],
   Timestamp('2025-04-12 00:00:00'): [0.7731774559563727, 0.8110931746788624],
   Timestamp('2025-04-19 00:00:00'): [0.7758447915645867, 0.7974607090709269],
   Timestamp('2025-04-26 00:00:00'): [0.7748280826278378, 0.7868582404532642]},
  15: {Timestamp('2024-11-30 00:00:00'): [0.6440208309618376,
    0.7514762759160323],
   Timestamp('2024-12-07 00:00:00'): [0.6409126457621951, 0.7444453760247514],
   Timestamp('2024-12-14 00:00:00'): [0.6398131391227798, 0.7375781082481669],
   Timestamp('2024-12-21 00:00:00'): [0.6430982480200598, 0.7326402596782234],
   Timestamp('2024-12-28 00:00:00'): [0.6330569891432504, 0.73940764307452],
   Timestamp('2025-01-04 00:00:00'): [0.6272043996715003, 0.7647028279964657],
   Timestamp('2025-01-11 00:00:00'): [0.6284835093280939, 0.7765903425670083],
   Timestamp('2025-01-18 00:00:00'): [0.6525964120996135, 0.7883116395242049],
   Timestamp('2025-02-01 00:00:00'): [0.6894843618850536, 0.8036813036590352],
   Timestamp('2025-02-08 00:00:00'): [0.7042847184975605, 0.8108280334147248],
   Timestamp('2025-02-15 00:00:00'): [0.7079716379352028, 0.8144796113574626],
   Timestamp('2025-02-22 00:00:00'): [0.7081515199055904, 0.8213379896443739],
   Timestamp('2025-03-01 00:00:00'): [0.7006791139183276, 0.8278092183545981],
   Timestamp('2025-03-08 00:00:00'): [0.698971286678545, 0.8321681347362905],
   Timestamp('2025-03-15 00:00:00'): [0.701962817308964, 0.8321149890307794],
   Timestamp('2025-03-22 00:00:00'): [0.71355046375522, 0.8278516916799459],
   Timestamp('2025-03-29 00:00:00'): [0.7187083293273276, 0.8202341428887191],
   Timestamp('2025-04-05 00:00:00'): [0.7417275480402986, 0.8184757677574004],
   Timestamp('2025-04-12 00:00:00'): [0.7555486149752846, 0.8110931746788624],
   Timestamp('2025-04-19 00:00:00'): [0.7587544133933436, 0.7974607090709269],
   Timestamp('2025-04-26 00:00:00'): [0.7631509481750227, 0.7868582404532642]},
  25: {Timestamp('2024-11-30 00:00:00'): [0.6494796802371314,
    0.7514762759160323],
   Timestamp('2024-12-07 00:00:00'): [0.646080719057879, 0.7444453760247514],
   Timestamp('2024-12-14 00:00:00'): [0.6503732570089484, 0.7375781082481669],
   Timestamp('2024-12-21 00:00:00'): [0.659822110467239, 0.7326402596782234],
   Timestamp('2024-12-28 00:00:00'): [0.6595016528677297, 0.73940764307452],
   Timestamp('2025-01-04 00:00:00'): [0.654832292411184, 0.7647028279964657],
   Timestamp('2025-01-11 00:00:00'): [0.653012175150787, 0.7765903425670083],
   Timestamp('2025-01-18 00:00:00'): [0.6707195831922295, 0.7883116395242049],
   Timestamp('2025-02-01 00:00:00'): [0.7073907380606175, 0.8036813036590352],
   Timestamp('2025-02-08 00:00:00'): [0.7200081854655832, 0.8108280334147248],
   Timestamp('2025-02-15 00:00:00'): [0.7241491777918794, 0.8144796113574626],
   Timestamp('2025-02-22 00:00:00'): [0.7214914746276931, 0.8213379896443739],
   Timestamp('2025-03-01 00:00:00'): [0.7109894410245298, 0.8278092183545981],
   Timestamp('2025-03-08 00:00:00'): [0.7052712070821242, 0.8321681347362905],
   Timestamp('2025-03-15 00:00:00'): [0.7110226798226005, 0.8321149890307794],
   Timestamp('2025-03-22 00:00:00'): [0.7203089347621624, 0.8278516916799459],
   Timestamp('2025-03-29 00:00:00'): [0.7276733952358255, 0.8202341428887191],
   Timestamp('2025-04-05 00:00:00'): [0.7474061735165293, 0.8184757677574004],
   Timestamp('2025-04-12 00:00:00'): [0.7572012955437394, 0.8110931746788624],
   Timestamp('2025-04-19 00:00:00'): [0.7590956625741516, 0.7974607090709269],
   Timestamp('2025-04-26 00:00:00'): [0.7603686679174092, 0.7868582404532642]},
  50: {Timestamp('2024-11-30 00:00:00'): [0.6630962001723191,
    0.7514762759160323],
   Timestamp('2024-12-07 00:00:00'): [0.6593601034013212, 0.7444453760247514],
   Timestamp('2024-12-14 00:00:00'): [0.6640607180454056, 0.7375781082481669],
   Timestamp('2024-12-21 00:00:00'): [0.6696063704689434, 0.7326402596782234],
   Timestamp('2024-12-28 00:00:00'): [0.6781733729103886, 0.73940764307452],
   Timestamp('2025-01-04 00:00:00'): [0.6851883663468119, 0.7647028279964657],
   Timestamp('2025-01-11 00:00:00'): [0.6861475217320423, 0.7765903425670083],
   Timestamp('2025-01-18 00:00:00'): [0.7022960683289254, 0.7883116395242049],
   Timestamp('2025-02-01 00:00:00'): [0.7332768738852141, 0.8036813036590352],
   Timestamp('2025-02-08 00:00:00'): [0.7391470980898922, 0.8108280334147248],
   Timestamp('2025-02-15 00:00:00'): [0.7427032315425942, 0.8144796113574626],
   Timestamp('2025-02-22 00:00:00'): [0.7374419259253417, 0.8213379896443739],
   Timestamp('2025-03-01 00:00:00'): [0.7322161522440557, 0.8278092183545981],
   Timestamp('2025-03-08 00:00:00'): [0.7334839284071711, 0.8321681347362905],
   Timestamp('2025-03-15 00:00:00'): [0.7432627151546036, 0.8321149890307794],
   Timestamp('2025-03-22 00:00:00'): [0.7498487804955785, 0.8278516916799459],
   Timestamp('2025-03-29 00:00:00'): [0.7531139009973497, 0.8202341428887191],
   Timestamp('2025-04-05 00:00:00'): [0.7676959660505169, 0.8184757677574004],
   Timestamp('2025-04-12 00:00:00'): [0.7733025782505921, 0.8110931746788624],
   Timestamp('2025-04-19 00:00:00'): [0.7697483407934781, 0.7974607090709269],
   Timestamp('2025-04-26 00:00:00'): [0.7662101956748063, 0.7868582404532642]},
  75: {Timestamp('2024-11-30 00:00:00'): [0.6988497270258849,
    0.7514762759160323],
   Timestamp('2024-12-07 00:00:00'): [0.6946870868086342, 0.7444453760247514],
   Timestamp('2024-12-14 00:00:00'): [0.6925152238317831, 0.7375781082481669],
   Timestamp('2024-12-21 00:00:00'): [0.697299522544029, 0.7326402596782234],
   Timestamp('2024-12-28 00:00:00'): [0.7139618137177933, 0.73940764307452],
   Timestamp('2025-01-04 00:00:00'): [0.7305027162381651, 0.7647028279964657],
   Timestamp('2025-01-11 00:00:00'): [0.7341657764359254, 0.7765903425670083],
   Timestamp('2025-01-18 00:00:00'): [0.7422999883599336, 0.7883116395242049],
   Timestamp('2025-02-01 00:00:00'): [0.7634290216595675, 0.8036813036590352],
   Timestamp('2025-02-08 00:00:00'): [0.768735148394381, 0.8108280334147248],
   Timestamp('2025-02-15 00:00:00'): [0.769897865647398, 0.8144796113574626],
   Timestamp('2025-02-22 00:00:00'): [0.7715516784592462, 0.8213379896443739],
   Timestamp('2025-03-01 00:00:00'): [0.7748758695769556, 0.8278092183545981],
   Timestamp('2025-03-08 00:00:00'): [0.7820347022920608, 0.8321681347362905],
   Timestamp('2025-03-15 00:00:00'): [0.7880854386670592, 0.8321149890307794],
   Timestamp('2025-03-22 00:00:00'): [0.7881427862795114, 0.8278516916799459],
   Timestamp('2025-03-29 00:00:00'): [0.7830631980972573, 0.8202341428887191],
   Timestamp('2025-04-05 00:00:00'): [0.7844298781582869, 0.8184757677574004],
   Timestamp('2025-04-12 00:00:00'): [0.7786662209571591, 0.8110931746788624],
   Timestamp('2025-04-19 00:00:00'): [0.7686444396866526, 0.7974607090709269],
   Timestamp('2025-04-26 00:00:00'): [0.7615534309719976,
    0.7868582404532642]}},
 '56': {5: {Timestamp('2024-11-30 00:00:00'): [0.6808636601541985,
    0.7971800544793414],
   Timestamp('2024-12-07 00:00:00'): [0.7251543329372796, 0.7894198192181987],
   Timestamp('2024-12-14 00:00:00'): [0.7766205046538946, 0.7715676454840298],
   Timestamp('2024-12-21 00:00:00'): [0.6407217677160278, 0.7945198099972027],
   Timestamp('2024-12-28 00:00:00'): [0.799146929677439, 0.7862653487333862],
   Timestamp('2025-01-04 00:00:00'): [0.6088833761935586, 0.8000285854274194],
   Timestamp('2025-01-11 00:00:00'): [0.6172179321596075, 0.8043549446993631],
   Timestamp('2025-01-18 00:00:00'): [0.6877917728392277, 0.8196920941253303],
   Timestamp('2025-02-01 00:00:00'): [0.746394509588601, 0.8466472877858802],
   Timestamp('2025-02-08 00:00:00'): [0.7525473584692713, 0.858568449291005],
   Timestamp('2025-02-15 00:00:00'): [0.762712910691712, 0.8680088590882983],
   Timestamp('2025-02-22 00:00:00'): [0.774451646552121, 0.8836356780961659],
   Timestamp('2025-03-01 00:00:00'): [0.7646286239352998, 0.881059380907298],
   Timestamp('2025-03-08 00:00:00'): [0.7937780287275629, 0.8981240477716287],
   Timestamp('2025-03-15 00:00:00'): [0.8144861428900163, 0.9121983894324838],
   Timestamp('2025-03-22 00:00:00'): [0.8160377547442718, 0.9146672561954656],
   Timestamp('2025-03-29 00:00:00'): [0.8156602452379692, 0.9142488817729648],
   Timestamp('2025-04-05 00:00:00'): [0.7784270501241094, 0.9002539325919845],
   Timestamp('2025-04-12 00:00:00'): [0.776636370213837, 0.8835988193866368],
   Timestamp('2025-04-19 00:00:00'): [0.7938817207040596, 0.9375306926520738],
   Timestamp('2025-04-26 00:00:00'): [0.8642167524254869, 0.9627814476540967]},
  15: {Timestamp('2024-11-30 00:00:00'): [0.6901108255966055,
    0.7971800544793414],
   Timestamp('2024-12-07 00:00:00'): [0.6994475273354187, 0.7894198192181987],
   Timestamp('2024-12-14 00:00:00'): [0.7409459012334204, 0.7715676454840298],
   Timestamp('2024-12-21 00:00:00'): [0.6805353094850314, 0.7945198099972027],
   Timestamp('2024-12-28 00:00:00'): [0.7644338798779784, 0.7862653487333862],
   Timestamp('2025-01-04 00:00:00'): [0.6498924194832316, 0.8000285854274194],
   Timestamp('2025-01-11 00:00:00'): [0.6441986395166767, 0.8043549446993631],
   Timestamp('2025-01-18 00:00:00'): [0.6884073657202071, 0.8196920941253303],
   Timestamp('2025-02-01 00:00:00'): [0.7625044882650478, 0.8466472877858802],
   Timestamp('2025-02-08 00:00:00'): [0.7775868461582454, 0.858568449291005],
   Timestamp('2025-02-15 00:00:00'): [0.7945264849054194, 0.8680088590882983],
   Timestamp('2025-02-22 00:00:00'): [0.8051499054438779, 0.8836356780961659],
   Timestamp('2025-03-01 00:00:00'): [0.7988294056067218, 0.881059380907298],
   Timestamp('2025-03-08 00:00:00'): [0.8232848755881019, 0.8981240477716287],
   Timestamp('2025-03-15 00:00:00'): [0.8424681878073348, 0.9121983894324838],
   Timestamp('2025-03-22 00:00:00'): [0.8385907109634222, 0.9146672561954656],
   Timestamp('2025-03-29 00:00:00'): [0.83700995651021, 0.9142488817729648],
   Timestamp('2025-04-05 00:00:00'): [0.8046723734706995, 0.9002539325919845],
   Timestamp('2025-04-12 00:00:00'): [0.7853173595590935, 0.8835988193866368],
   Timestamp('2025-04-19 00:00:00'): [0.8206683023731793, 0.9375306926520738],
   Timestamp('2025-04-26 00:00:00'): [0.8783223543714119, 0.9627814476540967]},
  25: {Timestamp('2024-11-30 00:00:00'): [0.7036785069668283,
    0.7971800544793414],
   Timestamp('2024-12-07 00:00:00'): [0.7093071752767074, 0.7894198192181987],
   Timestamp('2024-12-14 00:00:00'): [0.7248004940667175, 0.7715676454840298],
   Timestamp('2024-12-21 00:00:00'): [0.6958706401540008, 0.7945198099972027],
   Timestamp('2024-12-28 00:00:00'): [0.7531968284491779, 0.7862653487333862],
   Timestamp('2025-01-04 00:00:00'): [0.6762721012945224, 0.8000285854274194],
   Timestamp('2025-01-11 00:00:00'): [0.6681456069114987, 0.8043549446993631],
   Timestamp('2025-01-18 00:00:00'): [0.7091885437277085, 0.8196920941253303],
   Timestamp('2025-02-01 00:00:00'): [0.7673966084367366, 0.8466472877858802],
   Timestamp('2025-02-08 00:00:00'): [0.7875137834319798, 0.858568449291005],
   Timestamp('2025-02-15 00:00:00'): [0.8084642834487551, 0.8680088590882983],
   Timestamp('2025-02-22 00:00:00'): [0.82632017899073, 0.8836356780961659],
   Timestamp('2025-03-01 00:00:00'): [0.810900007922384, 0.881059380907298],
   Timestamp('2025-03-08 00:00:00'): [0.8354762336541298, 0.8981240477716287],
   Timestamp('2025-03-15 00:00:00'): [0.8534236653583369, 0.9121983894324838],
   Timestamp('2025-03-22 00:00:00'): [0.8491235446558831, 0.9146672561954656],
   Timestamp('2025-03-29 00:00:00'): [0.8444187756617554, 0.9142488817729648],
   Timestamp('2025-04-05 00:00:00'): [0.8135918174355206, 0.9002539325919845],
   Timestamp('2025-04-12 00:00:00'): [0.7880775333194312, 0.8835988193866368],
   Timestamp('2025-04-19 00:00:00'): [0.8367762610549155, 0.9375306926520738],
   Timestamp('2025-04-26 00:00:00'): [0.8856140524596096, 0.9627814476540967]},
  50: {Timestamp('2024-11-30 00:00:00'): [0.7251482768875098,
    0.7971800544793414],
   Timestamp('2024-12-07 00:00:00'): [0.7280461170644656, 0.7894198192181987],
   Timestamp('2024-12-14 00:00:00'): [0.7387708102757891, 0.7715676454840298],
   Timestamp('2024-12-21 00:00:00'): [0.7287397295917579, 0.7945198099972027],
   Timestamp('2024-12-28 00:00:00'): [0.7579141700843863, 0.7862653487333862],
   Timestamp('2025-01-04 00:00:00'): [0.7222401258220605, 0.8000285854274194],
   Timestamp('2025-01-11 00:00:00'): [0.7097997379369815, 0.8043549446993631],
   Timestamp('2025-01-18 00:00:00'): [0.7406906001370609, 0.8196920941253303],
   Timestamp('2025-02-01 00:00:00'): [0.7892226245413706, 0.8466472877858802],
   Timestamp('2025-02-08 00:00:00'): [0.8036225993617077, 0.858568449291005],
   Timestamp('2025-02-15 00:00:00'): [0.818787143898584, 0.8680088590882983],
   Timestamp('2025-02-22 00:00:00'): [0.8389763874948181, 0.8836356780961659],
   Timestamp('2025-03-01 00:00:00'): [0.8313700385051451, 0.881059380907298],
   Timestamp('2025-03-08 00:00:00'): [0.8533931823433448, 0.8981240477716287],
   Timestamp('2025-03-15 00:00:00'): [0.8701618517383962, 0.9121983894324838],
   Timestamp('2025-03-22 00:00:00'): [0.8659663334179956, 0.9146672561954656],
   Timestamp('2025-03-29 00:00:00'): [0.8608046846541518, 0.9142488817729648],
   Timestamp('2025-04-05 00:00:00'): [0.834434730169138, 0.9002539325919845],
   Timestamp('2025-04-12 00:00:00'): [0.8038550428816751, 0.8835988193866368],
   Timestamp('2025-04-19 00:00:00'): [0.8770192897351526, 0.9375306926520738],
   Timestamp('2025-04-26 00:00:00'): [0.922251515497294, 0.9627814476540967]},
  75: {Timestamp('2024-11-30 00:00:00'): [0.7530259130522435,
    0.7971800544793414],
   Timestamp('2024-12-07 00:00:00'): [0.7492611010988649, 0.7894198192181987],
   Timestamp('2024-12-14 00:00:00'): [0.7421335156803212, 0.7715676454840298],
   Timestamp('2024-12-21 00:00:00'): [0.7575072821639566, 0.7945198099972027],
   Timestamp('2024-12-28 00:00:00'): [0.7608755832350153, 0.7862653487333862],
   Timestamp('2025-01-04 00:00:00'): [0.7566605815092747, 0.8000285854274194],
   Timestamp('2025-01-11 00:00:00'): [0.7519594934830394, 0.8043549446993631],
   Timestamp('2025-01-18 00:00:00'): [0.7734188077926151, 0.8196920941253303],
   Timestamp('2025-02-01 00:00:00'): [0.8124392881284191, 0.8466472877858802],
   Timestamp('2025-02-08 00:00:00'): [0.8276941085752029, 0.858568449291005],
   Timestamp('2025-02-15 00:00:00'): [0.8397065285048022, 0.8680088590882983],
   Timestamp('2025-02-22 00:00:00'): [0.8581526056614242, 0.8836356780961659],
   Timestamp('2025-03-01 00:00:00'): [0.8544661257906144, 0.881059380907298],
   Timestamp('2025-03-08 00:00:00'): [0.8721858837540738, 0.8981240477716287],
   Timestamp('2025-03-15 00:00:00'): [0.886131631096284, 0.9121983894324838],
   Timestamp('2025-03-22 00:00:00'): [0.8835466674807533, 0.9146672561954656],
   Timestamp('2025-03-29 00:00:00'): [0.8806823248318819, 0.9142488817729648],
   Timestamp('2025-04-05 00:00:00'): [0.8572555251087342, 0.9002539325919845],
   Timestamp('2025-04-12 00:00:00'): [0.8290477383401135, 0.8835988193866368],
   Timestamp('2025-04-19 00:00:00'): [0.9019233684443794, 0.9375306926520738],
   Timestamp('2025-04-26 00:00:00'): [0.9393335122263402,
    0.9627814476540967]}},
 '29': {5: {Timestamp('2024-11-30 00:00:00'): [0.6608622169282545,
    0.7685310679158753],
   Timestamp('2024-12-07 00:00:00'): [0.698567432211539, 0.7594225807047608],
   Timestamp('2024-12-14 00:00:00'): [0.7121729606403359, 0.7465650216667348],
   Timestamp('2024-12-21 00:00:00'): [0.7338379030388793, 0.7309252414268774],
   Timestamp('2024-12-28 00:00:00'): [0.7031557746902568, 0.7299337584225257],
   Timestamp('2025-01-04 00:00:00'): [0.6144284526573387, 0.7545357726663844],
   Timestamp('2025-01-11 00:00:00'): [0.6274173766963903, 0.7710401905743691],
   Timestamp('2025-01-18 00:00:00'): [0.6651993795192869, 0.7885672918082688],
   Timestamp('2025-02-01 00:00:00'): [0.7739644710537974, 0.8281311531020802],
   Timestamp('2025-02-08 00:00:00'): [0.7832330691135221, 0.8401253572666758],
   Timestamp('2025-02-15 00:00:00'): [0.7844655032611907, 0.842666598033569],
   Timestamp('2025-02-22 00:00:00'): [0.7799268637525609, 0.8391424879415478],
   Timestamp('2025-03-01 00:00:00'): [0.7573265973990256, 0.8252059498226605],
   Timestamp('2025-03-08 00:00:00'): [0.7261971408814444, 0.8197756958205071],
   Timestamp('2025-03-15 00:00:00'): [0.7255127608081179, 0.809296347269994],
   Timestamp('2025-03-22 00:00:00'): [0.744468852442808, 0.8117196800715055],
   Timestamp('2025-03-29 00:00:00'): [0.7436633075242908, 0.8036397641707425],
   Timestamp('2025-04-05 00:00:00'): [0.7748500111223208, 0.8191552999708441],
   Timestamp('2025-04-12 00:00:00'): [0.7949101715648081, 0.835196813639251],
   Timestamp('2025-04-19 00:00:00'): [0.8170249804743837, 0.850377636144958],
   Timestamp('2025-04-26 00:00:00'): [0.8094716691516439, 0.8452990470961005]},
  15: {Timestamp('2024-11-30 00:00:00'): [0.6709508884228957,
    0.7685310679158753],
   Timestamp('2024-12-07 00:00:00'): [0.6735644892508861, 0.7594225807047608],
   Timestamp('2024-12-14 00:00:00'): [0.6786060867832567, 0.7465650216667348],
   Timestamp('2024-12-21 00:00:00'): [0.7086592469440309, 0.7309252414268774],
   Timestamp('2024-12-28 00:00:00'): [0.690784347874169, 0.7299337584225257],
   Timestamp('2025-01-04 00:00:00'): [0.6469145083864705, 0.7545357726663844],
   Timestamp('2025-01-11 00:00:00'): [0.6626616436799466, 0.7710401905743691],
   Timestamp('2025-01-18 00:00:00'): [0.7019662098242547, 0.7885672918082688],
   Timestamp('2025-02-01 00:00:00'): [0.7760207914272282, 0.8281311531020802],
   Timestamp('2025-02-08 00:00:00'): [0.7815571947365294, 0.8401253572666758],
   Timestamp('2025-02-15 00:00:00'): [0.7907132167617611, 0.842666598033569],
   Timestamp('2025-02-22 00:00:00'): [0.7910444845948713, 0.8391424879415478],
   Timestamp('2025-03-01 00:00:00'): [0.7681022154204366, 0.8252059498226605],
   Timestamp('2025-03-08 00:00:00'): [0.7624831001159493, 0.8197756958205071],
   Timestamp('2025-03-15 00:00:00'): [0.7617288249960873, 0.809296347269994],
   Timestamp('2025-03-22 00:00:00'): [0.7713412743768738, 0.8117196800715055],
   Timestamp('2025-03-29 00:00:00'): [0.7635601152639607, 0.8036397641707425],
   Timestamp('2025-04-05 00:00:00'): [0.7877747286928489, 0.8191552999708441],
   Timestamp('2025-04-12 00:00:00'): [0.80387844171009, 0.835196813639251],
   Timestamp('2025-04-19 00:00:00'): [0.8239675069709991, 0.850377636144958],
   Timestamp('2025-04-26 00:00:00'): [0.8169971137429817, 0.8452990470961005]},

In [37]:
rows = []

for state, k_group_data in dict_k_wis_rounds_states.items():
    for k, group_data in k_group_data.items():
        for timestamp, values in group_data.items():
            rows.append({
                'state': state,
                'k_perc': k,
                'week': timestamp.strftime('%Y-%m-%d'),
                'wis_adaptive_ensemble2': values[0],
                'wis_original_ensemble2': values[1],
            })

# Create DataFrame
df_wis = pd.DataFrame(rows)
df_wis.to_csv(f'../output_data/performance_adaptive_ensemble/wis_adaptive_ensemble2_wmape_{season}.csv', index=False)

In [38]:
rows = []

for state, k_group_data in dict_k_mae_rounds_states.items():
    for k, group_data in k_group_data.items():
        for timestamp, values in group_data.items():
            rows.append({
                'state': state,
                'k_perc': k,
                'week': timestamp.strftime('%Y-%m-%d'),
                'mae_adaptive_ensemble2': values[0],
                'mae_original_ensemble2': values[1],
            })

# Create DataFrame
df_mae = pd.DataFrame(rows)
df_mae.to_csv(f'../output_data/performance_adaptive_ensemble/mae_adaptive_ensemble2_wmape_{season}.csv', index=False)

In [8]:
season = '2023-2024'
if season == "2023-2024":
    df_wis = pd.read_csv(f'../output_data/performance_adaptive_ensemble/wis_adaptive_ensemble2_wmape.csv')
    df_mae = pd.read_csv(f'../output_data/performance_adaptive_ensemble/mae_adaptive_ensemble2_wmape.csv')
else:
    df_wis = pd.read_csv(f'../output_data/performance_adaptive_ensemble/wis_adaptive_ensemble2_wmape_{season}.csv')
    df_mae = pd.read_csv(f'../output_data/performance_adaptive_ensemble/mae_adaptive_ensemble2_wmape_{season}.csv')

In [9]:
if season == '2024-2025':
    df_wis = df_wis[df_wis['week'] <= '2025-03-22']
    df_mae = df_mae[df_mae['week'] <= '2025-03-22']
else:
    df_wis = df_wis[df_wis['week'] >= '2023-11-11']
    df_mae = df_mae[df_mae['week'] >= '2023-11-11']
    df_wis = df_wis[df_wis['week'] <= '2024-03-23']
    df_mae = df_mae[df_mae['week'] <= '2024-03-23']

In [ ]:
# remove puerto rico from the statistics
df_wis = df_wis[df_wis['state']!= 72]
df_mae = df_mae[df_mae['state']!= 72]

In [11]:
df_wis['wis_ratio'] = df_wis['wis_adaptive_ensemble2'] / df_wis['wis_original_ensemble2']

In [12]:
df_wis_25 = df_wis[df_wis['k_perc'] == 25]
df_wis_25_median = df_wis_25.groupby('state').agg({'wis_ratio': 'median'})
len(df_wis_25_median[df_wis_25_median.wis_ratio < 1])

38

In [13]:
df_mae['mae_ratio'] = df_mae['mae_adaptive_ensemble2'] / df_mae['mae_original_ensemble2']
df_mae_25 = df_mae[df_mae['k_perc'] == 25]
df_mae_25_median = df_mae_25.groupby('state').agg({'mae_ratio': 'median'})
len(df_mae_25_median[df_mae_25_median.mae_ratio < 1])

40